spring.application.name=MallManagement

# MySQL Configuration
# Update 'username' and 'password' to match your local MySQL installation
spring.datasource.url=jdbc:mysql://localhost:3306/mall_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Banana123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect